---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/personal_website
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
